### PR TITLE
Update: Contrast Edits

### PR DESCRIPTION
**Pull request by RuKira**
- Updated listing.blade.php
- Updated show.blade.php

To give a summary of what is changed, I basically updated some bg-white to be bg-gray-50 and darken some other text/colors. I made some blues more blue, and such. It's very minor changes, and should not really be noticeable except for contrasting each other.

# Default:
### Light
image
image
## Dark
image
image

# Updated:
## Light
image
image
### Dark
image
image

Keep this PR open so I can make edits and still verify things.
On the off chance these are not dark/light enough edits can be made to fix that.
Also I can edit other views to follow the same scheme, in this same PR.

### CODE REVIEW

**Comment by RuKira** [comment]
~~Now to go fix my GPG key.~~
Fixed.

**Comment by RuKira** [comment]
Ahah! Git auto merged, I need to remake this PR how fun.
That is my fault, was trying to test something

**Comment by refringe** [comment]
These look good! When you think it's in a good place mark it for review. :)

**Comment by RuKira** [comment]
~~@refringe the question here is would like me to just do these two for now and come back to others later? or more...~~

~~If you are ok with these two for now, I'll mark it now.~~

I'll mark it, I can always just make another PR for any other edits tbh.

You might have to cherry pick also, since I accidently merged main into this.. :/

**Comment by refringe** [comment]
Related to #30

@RuKira Before I merge, can you pull the latest changes to `develop` into your fork, rebase your fork branch `contrast-changes` on those latest changes, and then force-push your branch back up?

**Pull request closed without merging**
